version: '3'

services:
  php-fpm:
    container_name: news-php-fpm
    build: ./docker/php-fpm
    volumes:
      - ./:/var/
    depends_on:
      - mysql
  nginx:
    container_name: news-nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
  mysql:
    image: mysql:8
    container_name: news-mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user-news
        MYSQL_PASSWORD: pass-news
        MYSQL_DATABASE: news_app
